version: "3.7"

services:
  consul-server:
    image: hashicorp/consul:1.12.3
    container_name: consul-server
    restart: always
    networks:
      - standard
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0"

  consul-client:
    image: hashicorp/consul:1.12.3
    container_name: consul-client
    restart: always
    networks:
      - standard
    command: "agent -node=client-1 -join=consul-server"

networks:
  standard:
    driver: host
